version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video-media-player-web
    volumes: 
      - ".:/app"
    ports:
      - "0.0.0.0:8080:8080"