apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-10-01T23:13:38Z"
  generation: 1
  labels:
    app: video-media-player-web
  name: video-media-player-web
  namespace: default
  resourceVersion: "40213"
  selfLink: /apis/apps/v1/namespaces/default/deployments/video-media-player-web
  uid: 1acf2614-aedf-4e0b-8139-bea26e95d12e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: video-media-player-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: video-media-player-web
    spec:
      containers:
      - image: caprilespe/video-media-player-web:v1
        imagePullPolicy: IfNotPresent
        name: video-media-player-web
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-10-01T23:16:00Z"
    lastUpdateTime: "2021-10-01T23:16:00Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-10-01T23:13:38Z"
    lastUpdateTime: "2021-10-01T23:16:00Z"
    message: ReplicaSet "video-media-player-web-5c849b4589" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
