apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-10-01T23:20:42Z"
  labels:
    app: video-media-player-web
  name: video-media-player-web
  namespace: default
  resourceVersion: "40285"
  selfLink: /api/v1/namespaces/default/services/video-media-player-web
  uid: 73e56984-1451-4e75-b80a-6371fdd02650
spec:
  clusterIP: 10.102.65.135
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30931
    port: 8081
    protocol: TCP
    targetPort: 8080
  selector:
    app: video-media-player-web
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
